import { Project } from './project';

export const PROJECTS: Project[] = [
  {
    id: 6,
    title: 'Enhancing Site Search',
    subtitle: '',
    role: 'UX Design Lead : Arrow Digital',
    date: '2019',
    desc: '',
    tags: '',
    url: 'enhancing-site-search',
    cardImage: '/assets/img/card--img6.jpg',
  },
  {
    id: 5,
    title: 'Crushing Checkout Conversion',
    subtitle: '',
    role: 'UX Design Lead : Arrow Digital',
    date: '2019',
    desc: '',
    tags: '',
    url: 'crushing-checkout-conversion',
    cardImage: '/assets/img/card--img5.jpg',
  },
  {
    id: 4,
    title: 'Not a Robot',
    subtitle: '',
    role: 'Designer/Developer',
    date: '2019',
    desc: '',
    tags: '',
    url: 'not-a-robot',
    cardImage: '/assets/img/card--img4.jpg',
  },
  {
    id: 3,
    title: 'Jane Rae Interiors',
    subtitle: '',
    role: 'Designer/Developer',
    date: '2019',
    desc: '',
    tags: '',
    url: 'jane-rae-interiors',
    cardImage: '/assets/img/card--img3.jpg',
  },
  {
    id: 2,
    title: 'Past Development Projects',
    subtitle: '',
    role: 'Front End Developer',
    date: '2010 - 2018',
    desc: '',
    tags: '',
    url: 'past-development-projects',
    cardImage: '/assets/img/card--img2.jpg',
  },
  {
    id: 1,
    title: 'Past Design Projects',
    subtitle: '',
    role: 'Designer, etc.',
    date: '2010 - 2018',
    desc: '',
    tags: '',
    url: 'past-design-projects',
    cardImage: '/assets/img/card--img1.jpg',
  }
];
