import { Project } from './project';

export const PROJECTS: Project[] = [
  {
    id: 6,
    title: 'Enhancing Site Search',
    subtitle: '',
    role: 'UX Design Lead',
    client: 'Arrow Electronics',
    tools: 'Sketch, Invision, Pen & Paper',
    date: '2019',
    desc: '',
    tags: '',
    url: 'enhancing-site-search',
    alt: '',
    cardImage: './assets/img/card--img6.jpg',
  },
  {
    id: 5,
    title: 'Crushing Checkout Conversion',
    subtitle: '',
    role: 'UX Design Lead',
    client: 'Arrow Electronics',
    tools: 'Sketch, Invision, Pen & Paper',
    date: '2019',
    desc: '',
    tags: '',
    url: 'crushing-checkout-conversion',
    alt: '',
    cardImage: './assets/img/card--img5.jpg',
  },
  {
    id: 4,
    title: 'Not a Robot',
    subtitle: '',
    role: 'Designer and Developer',
    client: 'Not a Robot: Jamie Alberico SEO Specialist',
    tools: 'Sketch, HTML, SASS, Wordpress',
    date: '2019',
    desc: '',
    tags: '',
    url: 'not-a-robot',
    alt: '',
    cardImage: './assets/img/card--img4.jpg',
  },
  {
    id: 3,
    title: 'Jane Rae Interiors',
    subtitle: '',
    role: 'Designer and Developer',
    client: 'Jane Rae Interiors',
    tools: 'Sketch, HTML, SASS, Wordpress',
    date: '2019',
    desc: '',
    tags: '',
    url: 'jane-rae-interiors',
    alt: '',
    cardImage: './assets/img/card--img3.jpg',
  },
  {
    id: 2,
    title: 'Past Development Projects',
    subtitle: '',
    role: 'Front End Developer',
    client: 'Various Clients',
    tools: 'Various',
    date: '2010 - 2018',
    desc: '',
    tags: '',
    url: 'past-development-projects',
    alt: '',
    cardImage: './assets/img/card--img2.jpg',
  },
  {
    id: 1,
    title: 'Past Design Projects',
    subtitle: '',
    role: 'Art Direction, Designer',
    client: 'Various Clients',
    tools: 'Various',
    date: '2010 - 2018',
    desc: '',
    tags: '',
    url: 'past-design-projects',
    alt: '',
    cardImage: './assets/img/card--img1.jpg',
  }
];
